# Generated by Django 3.2.18 on 2023-04-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
