# Generated by Django 3.2.18 on 2023-04-24 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_checkout_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='email',
        ),
    ]
