# Generated by Django 3.2.18 on 2023-04-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_checkout_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
