# Generated by Django 3.2.18 on 2023-06-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20230613_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
