# Generated by Django 3.2.18 on 2023-06-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_cartitem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='mobile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
