# Generated by Django 3.2.18 on 2023-06-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_checkout_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='items',
        ),
    ]
